version: '3.6'

services:
  clean-arch-app:
      image: ${DOCKER_REGISTRY-}app
      container_name: clean-arc-app
      build:
        context: .
        dockerfile: .
      depends_on: 
        - database
      ports:
        - "5261:80"
      restart: always
      environment: 
        - DBHOST=database
        - ASPNETCORE_ENVIRONMENT=Development

  database:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: hw8vup5e
      MYSQL_USER: mac
      MYSQL_PASSWORD: hw8vup5e
      MYSQL_DATABASE: productsdb

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql

volumes:
  db-volume:

networks: 
  nt_mysql:
    driver: bridge